### ISSUE TITLE
SqliteError implementation broken

### ISSUE THREAD

**Issue by mgushee** [dckc/rust-sqlite3#18]
Hi, Dan--

Tried to build from Master w/ the latest Rust nightly. I got the following error message:
 
    src/lib.rs:324:5: 324:63 error: method `detail` is not a member of trait `Error`
    src/lib.rs:324     fn detail(&self) -> Option<String> { self.detail.clone() }  
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Apparently the `detail` field has been removed from `std::error::Error`. So I tried moving the `detail` method to a separate implementation, i.e.:

    impl SqliteError {
        fn detail(&self) -> Option<String> { self.detail.clone() }
    }

But that led to a new error:

    src/lib.rs:322:1: 325:2 error: the trait `core::fmt::String` is not implemented for the type `SqliteError` [E0277]
    src/lib.rs:322 impl Error for SqliteError {
    src/lib.rs:323     fn description(&self) -> &str { self.desc }
    src/lib.rs:324     fn cause(&self) -> Option<&Error> { None }
    src/lib.rs:325 }

Being a Rust newbie, I have no idea what to do with that. I thought it might be due to `println!` or `format`, being called with `{}`, but I tried changing every instance of `{}` to `{:?}`, and that didn't help.

Thanks for your good work!

**Comment by PeterReid** [comment]
This was fixed in 8166514092e27da8d953ed1086b69fc07adf3b6f.
