### ISSUE TITLE
Update crates.io?

### ISSUE THREAD

**Issue by PeterReid** [dckc/rust-sqlite3#29]
The version of this on crates.io is four months old and doesn't compile anymore. It would be nice to update it.

**Comment by dckc** [comment]
yeah; I've been thinking about that... today would be a good day ;-)

**Comment by dckc** [comment]
done: https://crates.io/crates/rust-sqlite/0.2.0

@PeterReid I tried to make you a co-owner, but I don't see how. Let me know if you figure it out.
