### ISSUE TITLE
support iterator trait

### ISSUE THREAD

**Issue by dckc** [dckc/rust-sqlite3#30]
@PeterReid, does the lifetime simplification (934d784) mean we can implement the Iterator trait now?

**Comment by PeterReid** [comment]
I don't think we can. The difficulty comes from preventing the from row being stepped past before sqlite3_column_x is lazily called on it, and the recent changes to controlling how sqlite3_close gets called don't affect that.

**Comment by dckc** [comment]
Bummer.

I took another look at how https://github.com/jgallagher/rusqlite handles this and I see a new `query_map()` method. @PeterReid. what do you think of that approach?

**Comment by dckc** [comment]
turns out this solution is effectively the same thing as that `query_map()`.
