### ISSUE TITLE
rust-ci docs lag

### ISSUE THREAD

**Issue by dckc** [dckc/rust-sqlite3#31]
Why won't http://www.rust-ci.org/dckc/rust-sqlite3/doc/sqlite3/ update?

**Comment by aij** [comment]
The `after_script` is failing with a syntax error (which Travis  CI conveniently hides by default):
https://travis-ci.org/dckc/rust-sqlite3/builds/63272513#L214

I'll  copy it here just in case it moves with the next update:

    $ curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100    27  100    27    0     0     35      0 --:--:-- --:--:-- --:--:--    42
    sh: 1: Syntax error: "(" unexpected
    Done. Your build exited with 0.

Do you know how to see what is actually being piped into `sh`?

One way to get a better idea what's going on there would be to replace `sh` with `sh -x`.

**Comment by aij** [comment]
One possible workaround would be to replace `sh` with `bash`, but this is just a wild guess and would imply a bug in the put script or the documentation for it.

Basically, I'm guessing `sh` got switched to be `dash`, which does not accept this function syntax:

    $ function foo () {
    sh: 1: Syntax error: "(" unexpected

**Comment by dckc** [comment]
I think rust-ci is passe. The new norm is to use github pages somehow...

**Comment by andreasfrom** [comment]
I've had success with github pages and `doc-upload` from [travis-cargo](https://github.com/huonw/travis-cargo) for what it's worth. I think the link to documentation should be removed from the readme though, it's confusing when it isn't updated.

**Comment by dckc** [comment]
In #42, @dgilman added travis-cargo support.

Unfortunately, I was already using github pages for my blog, and this technique seems to conflict. Any suggestions?

**Comment by andreasfrom** [comment]
No sorry, I don't how to handle that.

**Comment by dckc** [comment]
The docs seem to auto-update now.

I'm not sure how the conflict went away, but I don't really care.
