### ISSUE TITLE
split out sqlite3-sys ffi bindings crate?

### ISSUE THREAD

**Issue by dckc** [dckc/rust-sqlite3#32]
I gather there's a convention to have a separate crate for bindings; I don't have the details to hand just now, though.

**Comment by PeterReid** [comment]
The other sqlite3 package depends on https://crates.io/crates/libsqlite3-sys . Building using that on Windows requires a few steps, though -- downloading the sqlite3 source, building it with a compatible-with-rust gcc, and figuring out where to put the library. I would that that would be pretty irritating for someone downloading a package that depends on sqlite3 several packages deep. There is also the fact that what you end up building depends on the version of sqlite3 installed on the build system, so you can't know for sure if you have some of the most recent features (like WITH ... SELECT) available.

I made an alternative to that, though, that makes this a little less painful: https://github.com/PeterReid/sqlite3_static_sys . The sqlite3 source files are included, so you know what you are building against. A Windows user still needs gcc, but at least they get a nice error message from the gcc crate explaining what to do if they don't have it.

**Comment by dckc** [comment]
libsqlite3-sys is the sort of thing I had in mind. I'd like to see the Windows wart issue pushed upstream to the home of the -sys convention. I wonder if that would be the pkg-config crate.

cc @alexcrichton

**Comment by alexcrichton** [comment]
The current convention is for `libsqlite3-sys` crate's build script to do its best to find an existing `libsqlite3` on the system (e.g. through `pkg-config`), and failing that sometimes build from source (which is likely distributed with the crate itself).

**Comment by dckc** [comment]
This is now Somebody Else's Problem :)
See #46
