### ISSUE TITLE
Use thread-safe connection

### ISSUE THREAD

**Issue by singpolyma** [dckc/rust-sqlite3#37]
It is possible to have thread-safe sqlite3 connection handles, at which point DatabaseConnection could implement Sync and be shared between threads.

**Comment by dckc** [comment]
The rest of the data structures would have to be Sync too, yes? I wonder if I'll find time to think this thru...

**Comment by ericsink** [comment]
Seems problematic.

SQLite's thread safety supports three modes.  The Really Thread Safe mode (serialized) is often the default, but not always.  This depends on how the library was compiled.  And it is also possible to compile SQLite with this mode omitted from the build.

So if rust-sqlite3 is dynamically loading the sqlite3 library from "wherever", and I assume it is but have not checked, it cannot know how the library was compiled.

**Comment by dckc** [comment]
Actually, it could check with [sqlite3_threadsafe](https://www.sqlite.org/c3ref/threadsafe.html).

**Comment by dereckson** [comment]
> The rest of the data structures would have to be Sync too, yes?

Only the data structures used by `sqlite3::DatabaseConnection`.

So, the first candidate is  `std::rc::Rc<sqlite3::core::Database>`.

**Comment by dckc** [comment]
This is now Somebody Else's Problem :)
See #46
