### ISSUE TITLE
Change query return type to SqliteResult<A>

### ISSUE THREAD

**Issue by singpolyma** [dckc/rust-sqlite3#41]
It would be nice if I could build up a data structure during a query and then return it out the top, instead of having to use mutation.

**Comment by dckc** [comment]
That does sound nice; it's not obvious to me how it would work, though. Care to elaborate?

**Comment by singpolyma** [comment]
@dckc Well, the idea would basically be to make `query` act as a fold over the results instead of just an iterator.

**Comment by dckc** [comment]
Sorry, it's still not clear to me. Care to elaborate?

**Comment by singpolyma** [comment]
Here's how I've implemented it on top of the current API (obviously the real implementation with access to internals would probably be different than this, but you should be able to see the idea):

```
fn option_map_mut<T, F: FnOnce(T) -> T>(x: &mut Option<T>, f: F) {
	match *x {
		Some(_) => {
			*x = Some(f(x.take().unwrap()));
		}
		None => {}
	}
}

fn query_fold<T, F: Fn(&mut ResultRow, T) -> T>(z: T, q: &mut PreparedStatement, values: &[&ToSql], f: F) -> T
{
	let mut zbox = Some(z);

	q.query(values, &mut |row| {
		option_map_mut(&mut zbox, { |z| f(row, z) });
		Ok(())
	}).unwrap();

	zbox.unwrap()
}
```

**Comment by dckc** [comment]
Ah. I think I get it now.
